version: '3.8'

services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Hoaze1234#
    volumes:
      - mongodb_data:/data/db
    networks:
      - my-network

volumes:
  mongodb_data:

networks:
  my-network:
    external: true