version: "3.9"

services:
  web_air_quality:
    build: .
    container_name: web_air_quality
    env_file:
      - .env-docker
    networks:
      - bigdata-network
    ports:
      - "4000:4000"
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  bigdata-network:
    external: true